version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-type: "development"
    commit-message:
      prefix: "😨"
    labels:
      - "python-dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "😨"
    labels:
      - "github-actions-dependencies"

