version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      runtime-minors:
        patterns: ["*"]                 
        update-types: ["minor", "patch"] 
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    commit-message:
      prefix: "😨"
    labels:
      - "python-dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gha-minors:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    commit-message:
      prefix: "😨"
    labels:
      - "github-actions-dependencies"

