name: Docs
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install {{ vars.PYTHON_VERSION }} 
    
      - name: Set up venv
        run: |
          uv venv -p {{ vars.PYTHON_VERSION }} 
          uv pip install '.[docs]'

      - name: Run MKdocs
        run: uv run mkdocs gh-deploy --force
