name: Lint

on: 
  workflow_dispatch:
  pull_request:
  push:
      branches:
        - main

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ruff without running check or format
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
      
      - name: Run format check
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
          src: >-
            psengine
            tests
            tests_without_config
        
      - name: Run syntax check
        uses: astral-sh/ruff-action@v3
        with:
          src: >-
            psengine
            tests
            tests_without_config
          args: "check --ignore FIX"
