name: Sample Apps

on: 
  workflow_dispatch:

jobs:
  run-examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        apps: [
          "analyst_notes", 
          "base_http_client", 
          "classic_alerts", 
          "collective_insights", 
          "config", 
          "detection", 
          "enrichment", 
          "identity", 
          "lists", 
          "markdown", 
          "playbook_alerts", 
          "rf_client", 
          "risklists", 
          "stix2"
        ]
    env:
      RF_TOKEN: ${{ secrets.RF_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install {{ vars.PYTHON_VERSION }} 
      
      - name: Set up venv
        run: |
          uv venv -p {{ vars.PYTHON_VERSION }} 
          uv pip install '.'

      - name: Run ${{matrix.apps}}
        run: uv run python examples/${{matrix.apps}}/run_${{matrix.apps}}.py
